---
abstract: 'Parses a custom Mojo template file format'
author:
  - 'Erik Carlsson <csson@cpan.org>'
build_requires:
  Data::Dumper: '2.130'
  Test::Deep: '0.110'
  Test::More: '0.96'
configure_requires:
  Module::Build::Tiny: '0.037'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.5, Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MojoX-CustomTemplateFileParser
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Mojolicious: '5.00'
  Path::Tiny: '0.050'
  Storable: '2.24'
  perl: '5.010'
resources:
  bugtracker: https://github.com/Csson/p5-mojox-customtemplatefileparser/issues
  homepage: https://github.com/Csson/p5-mojox-customtemplatefileparser
  repository: https://github.com/Csson/p5-mojox-customtemplatefileparser.git
version: '0.03'
x_contributors:
  - 'Erik Carlsson <info@code301.com>'
